services:
  postgresql:
    image: postgres:17-alpine
    restart: always
    volumes:
      - ~/data/postgres/saumon-net:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foo
  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
  web:
    build: .
    volumes:
      - .:/rails
    depends_on:
        - postgresql
    environment:
      - POSTGRES_PASSWORD=foo
      - REDIS_URL=redis://redis:6379/0
      - REDIS_SIDEKIQ_URL=redis://redis:6379/1
    ports:
      - "3004:3000"
