anod.download_resource.completed:
  - job: AssembleeNationaleData::ProcessDownloadedResourceJob
    args:
      - :download_id
  - job: Telescope::LogJob
    args:
      - "download completed"
      - download_id: :download_id
        triggered_ts: :triggered_ts
anod.file_extraction.completed:
  - job: AssembleeNationaleData::UpsertEntityJob
    args:
      - :file_id
  - job: Telescope::LogJob
    args:
      - "file extraction completed"
      - file_id: :file_id
